"""unique answer per question in game

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 08:55:04.522080
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_quiz_attempts_session_question', 'quiz_attempts', ['session_id', 'question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_quiz_attempts_session_question', 'quiz_attempts', type_='unique')
    # ### end Alembic commands ###
